if: branch = master and type IN (pull_request)
language: cpp
services:
  - docker
env:
before_install:
  - docker pull fiware/orion-ci:rpm7
install: true
before_script: true
script: true
jobs:
  include:
    - stage: unit
      before_script: docker run -t --rm -v $(pwd):/opt/fiware-orion fiware/orion-ci:rpm7 build -M unit
      script: docker run -t --rm -v $(pwd):/opt/fiware-orion fiware/orion-ci:rpm7 build -IDu
    - stage: functional
      before_script: docker run -t --rm -v $(pwd):/opt/fiware-orion fiware/orion-ci:rpm7 build -M functional
      script: docker run -t --rm -v $(pwd):/opt/fiware-orion fiware/orion-ci:rpm7 build -IDFf
