if: branch = master and type IN (pull_request)
dist: trusty
sudo: required
language: minimal
services:
  - docker
env:
  matrix:
    - TEST=compliance
    - TEST=unit
    - TEST=functional
before_install: true
install: true
before_script:
  - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker pull fiware/orion-ci:rpm7
script:
  - if [ "$TEST" = "compliance" ]; then ci/rpm7/build.sh -s compliance -tp $(pwd); else docker run -t --rm -v $(pwd):/opt/fiware-orion fiware/orion-ci:rpm7 build -s $TEST -midt; fi
